apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ipAddress }}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-alt
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webapp 
